#
# Copyright 2018, Mokshasoft AB (mokshasoft.com)
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#

APP_NAME := hello-idris-1
apps-$(CONFIG_APP_HELLO_IDRIS_1) += $(APP_NAME)

# Set up variables for the Idris compilation
APP_DIR := $(SEL4_APPS_PATH)/$(APP_NAME)
IDRIS_FILES := $(wildcard $(APP_DIR)/src/*.idr)
IDRIS_APP_BUILD_DIR := $(BUILD_BASE)/$(APP_NAME)
IDRIS_GENERATED_APP_SRC := $(IDRIS_APP_BUILD_DIR)/$(APP_NAME).c
IDRIS_LIBS_DIRS := $(SEL4_LIBS_PATH)/idris-libsel4-ffi/src

# Compile the Idris code to C
$(APP_NAME).c: $(IDRIS_FILES)
	@echo "Compiling Idris code to C..."
	$(Q)mkdir -p $(IDRIS_APP_BUILD_DIR)
	$(Q)idris \
		--ibcsubdir $(IDRIS_APP_BUILD_DIR) \
		--idrispath $(APP_DIR)/src \
		$(addprefix --idrispath ,$(IDRIS_LIBS_DIRS)) \
		--codegen C --codegenonly -o $(IDRIS_GENERATED_APP_SRC) \
		$(APP_DIR)/src/Main.idr

# Libraries needed by the app
$(APP_NAME)-y = \
    common \
    libsel4 \
    libmuslc \
    libsel4muslcsys \
    libsel4platsupport \
    libsel4-idris-rts \
    libutils \
    libsel4utils \
    libsel4debug

# App
$(APP_NAME): \
    kernel_elf \
    $($(APP_NAME)-y) \
    $(APP_NAME).c
