#
# Copyright 2018, Mokshasoft AB (mokshasoft.com)
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#

apps-$(CONFIG_APP_HELLO_IDRIS_1) += hello-idris-1

this_dir := $(dir $(lastword $(MAKEFILE_LIST)))
include $(this_dir)/src/Kbuild

# Libraries needed by the app
hello-idris-1-y = \
    common \
    libsel4 \
    libmuslc \
    libsel4muslcsys \
    libsel4platsupport \
    libsel4-idris-rts \
    libutils \
    libsel4utils \
    libsel4debug \
    $(BUILD_BASE)/hello-idris-1/hello-idris-1.c

# App
hello-idris-1: \
    kernel_elf \
    $(hello-idris-1-y)
